server:
  applicationConnectors:
    - type: "http"
      port: 9000
  adminConnectors:
    - type: "http"
      port: 9001
  requestLog:
    appenders:
      - type: "file"
        currentLogFilename: "logs/access.log"
        archivedLogFilenamePattern: "logs/access.%d{yyyy-MM-dd}.log.gz"
  type: "default"

redis:
  type: basic
  name: vidya-backend-temp-storage
  node:
    type: redis
    node: "vidya.cctfbu.0001.use1.cache.amazonaws.com:6379"
    clientName: vidya-backend
  redisCodec:
    type: string
  clientResources:
    type: default
    commandLatencyCollector:
      type: default
      enabled: false

# TTL of one week
tokenTTL: 604800

database:
  driverClass: org.postgresql.Driver
  maxWaitForConnection: 1s
  validationQuery: "/* Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  checkConnectionOnBorrow: true
  validationInterval: 30s
  evictionInterval: 5s
  minIdleTime: 1 minute
  user: DB_USER
  password: DB_PASSWORD
  url: "DB_URL"
  properties:
    charSet: UTF-8
    applicationName: vidya-backend

s3:
  accessKeyId: S3_KEY
  secretAccessKey: S3_SECRET
  dataBucket: vidyadata
  awsRegion: us-east-1

logging:
  level: INFO
  loggers:
    io.vgaur: DEBUG
